// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdaqQnBmA7l_nCapA_s1mO23CsviqQXOM',
    appId: '1:696150681893:android:ec1c6189b039a0630192cc',
    messagingSenderId: '696150681893',
    projectId: 'e-commece-f9132',
    storageBucket: 'e-commece-f9132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-XUka53ui53FDo4gTG1fDkJmP7nCiou0',
    appId: '1:696150681893:ios:186d68170a2184f90192cc',
    messagingSenderId: '696150681893',
    projectId: 'e-commece-f9132',
    storageBucket: 'e-commece-f9132.firebasestorage.app',
    iosBundleId: 'com.example.eCommereceApp',
  );
}